<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../RulesCore.Application/RulesCore.Application.csproj" />
    <ProjectReference Include="../RulesCore.Domain/RulesCore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="BundledSources/*.json" />
  </ItemGroup>
</Project>
